"""
Constants file for Musidoku Django app
Contains country mappings, genre mappings, and other reusable constants
"""

# Genre mapping for normalizing Spotify genres
GENRE_MAPPING = {
    'Rap': 'Hip-Hop',
    'Pop': 'Pop',
    'Reggaeton': 'Latin',
    'Soft Pop': 'Pop',
    'Hip Hop': 'Hip-Hop',
    'Alternative': 'Alternative',
    'K-pop': ['K-Pop', 'Pop'],
    'Melodic Rap': 'Hip-Hop',
    'Hip-hop': 'Hip-Hop',
    'R&b': 'R&B',
    'Emo Rap': 'Hip-Hop',
    'Edm': 'Electronic',
    'R&B': 'R&B',
    'Art Pop': 'Pop',
    'Classic Rock': 'Rock',
    'Latin Pop': 'Latin',
    'Nu Metal': 'Rock',
    'Trap Soul': 'R&B',
    'Hindi Pop': 'Bollywood',
    'Corrido': 'Latin',
    'Indie': 'Alternative',
    'Country': 'Country',
    'Electronic': 'Electronic',
    'Bollywood': 'Bollywood',
    'Rage Rap': 'Hip-Hop',
    'Corridos Tumbados': 'Latin',
    'G-funk': 'Hip-Hop',
    'Tropical House': 'Electronic',
    'Funk Rock': 'Rock',
    'East Coast Hip Hop': 'Hip-Hop',
    'Rock': 'Rock',
    'Bachata': 'Latin',
    'Brooklyn Drill': 'Hip-Hop',
    'Metal': 'Metal',
    'Moombahton': 'Electronic',
    'Trap': 'Hip-Hop',
    'French House': 'Electronic',
    'Dancehall': 'Reggae',
    'Mariachi': 'Latin',
    'Chicago Drill': 'Hip-Hop',
    'Southern Hip Hop': 'Hip-Hop',
    'Argentine Trap': 'Latin',
    'Sertanejo': 'Latin',
    'Emo': 'Rock',
    'Banda': 'Latin',
    'Brazilian Pop': 'Latin',
    'Colombian Pop': 'Latin',
    'Singer-songwriter': 'Alternative',
    'Soul / Motown R&B': 'R&B',
    'Christian Hip Hop': 'Hip-Hop',
    'Old School Hip Hop': 'Hip-Hop',
    'Christmas': 'Pop',
    'French Rap': 'Hip-Hop',
    'Tamil Pop': 'Bollywood',
    'Grunge': 'Rock',
    'Punk': 'Rock',
    'Hyperpop': 'Pop',
    'Neo-psychedelic': 'Alternative',
    'Dubstep': 'Electronic',
    'Art Rock': 'Rock',
    'Progressive Rock': 'Rock',
    'Urbano Latino': 'Latin',
    'Cumbia Norteña': 'Latin',
    'Rockabilly': 'Rock',
    'Latin': 'Latin',
    'Dream Pop': 'Alternative',
}

# Country code to continent mapping
COUNTRY_CONTINENTS = {
    # North America
    'US': 'North America',
    'CA': 'North America',
    'MX': 'North America',
    'GL': 'North America',
    
    # Europe
    'GB': 'Europe',
    'FR': 'Europe', 
    'DE': 'Europe',
    'IT': 'Europe',
    'ES': 'Europe',
    'NL': 'Europe',
    'BE': 'Europe',
    'CH': 'Europe',
    'AT': 'Europe',
    'PT': 'Europe',
    'IE': 'Europe',
    'LU': 'Europe',
    'MC': 'Europe',
    'LI': 'Europe',
    'AD': 'Europe',
    'SM': 'Europe',
    'VA': 'Europe',
    'SE': 'Europe',
    'NO': 'Europe',
    'DK': 'Europe',
    'FI': 'Europe',
    'IS': 'Europe',
    'PL': 'Europe',
    'CZ': 'Europe',
    'HU': 'Europe',
    'RO': 'Europe',
    'BG': 'Europe',
    'HR': 'Europe',
    'SK': 'Europe',
    'SI': 'Europe',
    'EE': 'Europe',
    'LV': 'Europe',
    'LT': 'Europe',
    'RU': 'Europe',
    'UA': 'Europe',
    'BY': 'Europe',
    'MD': 'Europe',
    'RS': 'Europe',
    'BA': 'Europe',
    'ME': 'Europe',
    'MK': 'Europe',
    'AL': 'Europe',
    'XK': 'Europe',
    'GR': 'Europe',
    'MT': 'Europe',
    'CY': 'Europe',
    
    # Asia
    'CN': 'Asia',
    'JP': 'Asia',
    'KR': 'Asia',
    'KP': 'Asia',
    'MN': 'Asia',
    'TW': 'Asia',
    'HK': 'Asia',
    'MO': 'Asia',
    'TH': 'Asia',
    'VN': 'Asia',
    'PH': 'Asia',
    'ID': 'Asia',
    'MY': 'Asia',
    'SG': 'Asia',
    'MM': 'Asia',
    'KH': 'Asia',
    'LA': 'Asia',
    'TL': 'Asia',
    'BN': 'Asia',
    'IN': 'Asia',
    'PK': 'Asia',
    'BD': 'Asia',
    'LK': 'Asia',
    'NP': 'Asia',
    'BT': 'Asia',
    'MV': 'Asia',
    'AF': 'Asia',
    'KZ': 'Asia',
    'UZ': 'Asia',
    'TM': 'Asia',
    'TJ': 'Asia',
    'KG': 'Asia',
    'TR': 'Asia',
    'IR': 'Asia',
    'IQ': 'Asia',
    'SY': 'Asia',
    'JO': 'Asia',
    'LB': 'Asia',
    'IL': 'Asia',
    'PS': 'Asia',
    'SA': 'Asia',
    'AE': 'Asia',
    'KW': 'Asia',
    'QA': 'Asia',
    'BH': 'Asia',
    'OM': 'Asia',
    'YE': 'Asia',
    'GE': 'Asia',
    'AM': 'Asia',
    'AZ': 'Asia',
    
    # Oceania
    'AU': 'Oceania',
    'NZ': 'Oceania',
    'FJ': 'Oceania',
    'PG': 'Oceania',
    'SB': 'Oceania',
    'VU': 'Oceania',
    'NC': 'Oceania',
    'PF': 'Oceania',
    'WS': 'Oceania',
    'TO': 'Oceania',
    'CK': 'Oceania',
    'NU': 'Oceania',
    'KI': 'Oceania',
    'TV': 'Oceania',
    'NR': 'Oceania',
    'PW': 'Oceania',
    'FM': 'Oceania',
    'MH': 'Oceania',
    
    # South America
    'BR': 'South America',
    'AR': 'South America',
    'CL': 'South America',
    'UY': 'South America',
    'PY': 'South America',
    'CO': 'South America',
    'VE': 'South America',
    'GY': 'South America',
    'SR': 'South America',
    'GF': 'South America',
    'PE': 'South America',
    'EC': 'South America',
    'BO': 'South America',
    
    # Central America & Caribbean
    'GT': 'Central America & Caribbean',
    'BZ': 'Central America & Caribbean',
    'SV': 'Central America & Caribbean',
    'HN': 'Central America & Caribbean',
    'NI': 'Central America & Caribbean',
    'CR': 'Central America & Caribbean',
    'PA': 'Central America & Caribbean',
    'CU': 'Central America & Caribbean',
    'JM': 'Central America & Caribbean',
    'HT': 'Central America & Caribbean',
    'DO': 'Central America & Caribbean',
    'TT': 'Central America & Caribbean',
    'BB': 'Central America & Caribbean',
    'PR': 'Central America & Caribbean',
    'BS': 'Central America & Caribbean',
    'GD': 'Central America & Caribbean',
    'LC': 'Central America & Caribbean',
    'VC': 'Central America & Caribbean',
    'AG': 'Central America & Caribbean',
    'DM': 'Central America & Caribbean',
    'KN': 'Central America & Caribbean',
    
    # Africa
    'EG': 'Africa',
    'LY': 'Africa',
    'TN': 'Africa',
    'DZ': 'Africa',
    'MA': 'Africa',
    'SD': 'Africa',
    'NG': 'Africa',
    'GH': 'Africa',
    'SN': 'Africa',
    'ML': 'Africa',
    'BF': 'Africa',
    'NE': 'Africa',
    'CI': 'Africa',
    'GN': 'Africa',
    'SL': 'Africa',
    'LR': 'Africa',
    'MR': 'Africa',
    'GM': 'Africa',
    'GW': 'Africa',
    'CV': 'Africa',
    'TG': 'Africa',
    'BJ': 'Africa',
    'ET': 'Africa',
    'KE': 'Africa',
    'UG': 'Africa',
    'TZ': 'Africa',
    'RW': 'Africa',
    'BI': 'Africa',
    'SO': 'Africa',
    'DJ': 'Africa',
    'ER': 'Africa',
    'SS': 'Africa',
    'CD': 'Africa',
    'CF': 'Africa',
    'CM': 'Africa',
    'TD': 'Africa',
    'CG': 'Africa',
    'GA': 'Africa',
    'GQ': 'Africa',
    'ST': 'Africa',
    'ZA': 'Africa',
    'ZW': 'Africa',
    'BW': 'Africa',
    'NA': 'Africa',
    'ZM': 'Africa',
    'MW': 'Africa',
    'MZ': 'Africa',
    'SZ': 'Africa',
    'LS': 'Africa',
    'MG': 'Africa',
    'MU': 'Africa',
    'SC': 'Africa',
    'YT': 'Africa',
    'RE': 'Africa',
    'KM': 'Africa',
}

# Country code to sub-region mapping
COUNTRY_SUBREGIONS = {
    # North America
    'US': 'United States',
    'CA': 'Canada',
    'MX': 'Mexico',
    'GL': 'Greenland',
    
    # Europe - Western Europe
    'GB': 'Western Europe',
    'FR': 'Western Europe', 
    'DE': 'Western Europe',
    'IT': 'Western Europe',
    'ES': 'Western Europe',
    'NL': 'Western Europe',
    'BE': 'Western Europe',
    'CH': 'Western Europe',
    'AT': 'Western Europe',
    'PT': 'Western Europe',
    'IE': 'Western Europe',
    'LU': 'Western Europe',
    'MC': 'Western Europe',
    'LI': 'Western Europe',
    'AD': 'Western Europe',
    'SM': 'Western Europe',
    'VA': 'Western Europe',
    
    # Europe - Northern Europe
    'SE': 'Northern Europe',
    'NO': 'Northern Europe',
    'DK': 'Northern Europe',
    'FI': 'Northern Europe',
    'IS': 'Northern Europe',
    
    # Europe - Eastern Europe
    'PL': 'Eastern Europe',
    'CZ': 'Eastern Europe',
    'HU': 'Eastern Europe',
    'RO': 'Eastern Europe',
    'BG': 'Eastern Europe',
    'HR': 'Eastern Europe',
    'SK': 'Eastern Europe',
    'SI': 'Eastern Europe',
    'EE': 'Eastern Europe',
    'LV': 'Eastern Europe',
    'LT': 'Eastern Europe',
    'RU': 'Eastern Europe',
    'UA': 'Eastern Europe',
    'BY': 'Eastern Europe',
    'MD': 'Eastern Europe',
    'RS': 'Eastern Europe',
    'BA': 'Eastern Europe',
    'ME': 'Eastern Europe',
    'MK': 'Eastern Europe',
    'AL': 'Eastern Europe',
    'XK': 'Eastern Europe',
    
    # Europe - Southern Europe
    'GR': 'Southern Europe',
    'MT': 'Southern Europe',
    'CY': 'Southern Europe',
    
    # Asia - East Asia
    'CN': 'East Asia',
    'JP': 'East Asia',
    'KR': 'East Asia',
    'KP': 'East Asia',
    'MN': 'East Asia',
    'TW': 'East Asia',
    'HK': 'East Asia',
    'MO': 'East Asia',
    
    # Asia - Southeast Asia
    'TH': 'Southeast Asia',
    'VN': 'Southeast Asia',
    'PH': 'Southeast Asia',
    'ID': 'Southeast Asia',
    'MY': 'Southeast Asia',
    'SG': 'Southeast Asia',
    'MM': 'Southeast Asia',
    'KH': 'Southeast Asia',
    'LA': 'Southeast Asia',
    'TL': 'Southeast Asia',
    'BN': 'Southeast Asia',
    
    # Asia - South Asia
    'IN': 'South Asia',
    'PK': 'South Asia',
    'BD': 'South Asia',
    'LK': 'South Asia',
    'NP': 'South Asia',
    'BT': 'South Asia',
    'MV': 'South Asia',
    'AF': 'South Asia',
    
    # Asia - Central Asia
    'KZ': 'Central Asia',
    'UZ': 'Central Asia',
    'TM': 'Central Asia',
    'TJ': 'Central Asia',
    'KG': 'Central Asia',
    
    # Asia - Western Asia (Middle East)
    'TR': 'Western Asia',
    'IR': 'Western Asia',
    'IQ': 'Western Asia',
    'SY': 'Western Asia',
    'JO': 'Western Asia',
    'LB': 'Western Asia',
    'IL': 'Western Asia',
    'PS': 'Western Asia',
    'SA': 'Western Asia',
    'AE': 'Western Asia',
    'KW': 'Western Asia',
    'QA': 'Western Asia',
    'BH': 'Western Asia',
    'OM': 'Western Asia',
    'YE': 'Western Asia',
    'GE': 'Western Asia',
    'AM': 'Western Asia',
    'AZ': 'Western Asia',
    
    # Oceania
    'AU': 'Australia & New Zealand',
    'NZ': 'Australia & New Zealand',
    'FJ': 'Pacific Islands',
    'PG': 'Pacific Islands',
    'SB': 'Pacific Islands',
    'VU': 'Pacific Islands',
    'NC': 'Pacific Islands',
    'PF': 'Pacific Islands',
    'WS': 'Pacific Islands',
    'TO': 'Pacific Islands',
    'CK': 'Pacific Islands',
    'NU': 'Pacific Islands',
    'KI': 'Pacific Islands',
    'TV': 'Pacific Islands',
    'NR': 'Pacific Islands',
    'PW': 'Pacific Islands',
    'FM': 'Pacific Islands',
    'MH': 'Pacific Islands',
    
    # South America
    'BR': 'Brazil',
    'AR': 'Southern Cone',
    'CL': 'Southern Cone',
    'UY': 'Southern Cone',
    'PY': 'Southern Cone',
    'CO': 'Northern Countries',
    'VE': 'Northern Countries',
    'GY': 'Northern Countries',
    'SR': 'Northern Countries',
    'GF': 'Northern Countries',
    'PE': 'Andean Countries',
    'EC': 'Andean Countries',
    'BO': 'Andean Countries',
    
    # Central America & Caribbean
    'GT': 'Central America',
    'BZ': 'Central America',
    'SV': 'Central America',
    'HN': 'Central America',
    'NI': 'Central America',
    'CR': 'Central America',
    'PA': 'Central America',
    'CU': 'Caribbean',
    'JM': 'Caribbean',
    'HT': 'Caribbean',
    'DO': 'Caribbean',
    'TT': 'Caribbean',
    'BB': 'Caribbean',
    'PR': 'Caribbean',
    'BS': 'Caribbean',
    'GD': 'Caribbean',
    'LC': 'Caribbean',
    'VC': 'Caribbean',
    'AG': 'Caribbean',
    'DM': 'Caribbean',
    'KN': 'Caribbean',
    
    # Africa - North Africa
    'EG': 'North Africa',
    'LY': 'North Africa',
    'TN': 'North Africa',
    'DZ': 'North Africa',
    'MA': 'North Africa',
    'SD': 'North Africa',
    
    # Africa - West Africa
    'NG': 'West Africa',
    'GH': 'West Africa',
    'SN': 'West Africa',
    'ML': 'West Africa',
    'BF': 'West Africa',
    'NE': 'West Africa',
    'CI': 'West Africa',
    'GN': 'West Africa',
    'SL': 'West Africa',
    'LR': 'West Africa',
    'MR': 'West Africa',
    'GM': 'West Africa',
    'GW': 'West Africa',
    'CV': 'West Africa',
    'TG': 'West Africa',
    'BJ': 'West Africa',
    
    # Africa - East Africa
    'ET': 'East Africa',
    'KE': 'East Africa',
    'UG': 'East Africa',
    'TZ': 'East Africa',
    'RW': 'East Africa',
    'BI': 'East Africa',
    'SO': 'East Africa',
    'DJ': 'East Africa',
    'ER': 'East Africa',
    'SS': 'East Africa',
    
    # Africa - Central Africa
    'CD': 'Central Africa',
    'CF': 'Central Africa',
    'CM': 'Central Africa',
    'TD': 'Central Africa',
    'CG': 'Central Africa',
    'GA': 'Central Africa',
    'GQ': 'Central Africa',
    'ST': 'Central Africa',
    
    # Africa - Southern Africa
    'ZA': 'Southern Africa',
    'ZW': 'Southern Africa',
    'BW': 'Southern Africa',
    'NA': 'Southern Africa',
    'ZM': 'Southern Africa',
    'MW': 'Southern Africa',
    'MZ': 'Southern Africa',
    'SZ': 'Southern Africa',
    'LS': 'Southern Africa',
    'MG': 'Southern Africa',
    'MU': 'Southern Africa',
    'SC': 'Southern Africa',
    'YT': 'Southern Africa',
    'RE': 'Southern Africa',
    'KM': 'Southern Africa',
}