# Generated by Django 5.2.4 on 2025-07-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labels',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
