# Generated by Django 5.2.4 on 2025-08-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_artists_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
    ]
