# Generated by Django 5.2.4 on 2025-09-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_artists_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artists",
            name="image",
        ),
        migrations.AddField(
            model_name="artists",
            name="cached_image_url",
            field=models.URLField(
                blank=True, help_text="Cached image URL from Spotify", null=True
            ),
        ),
        migrations.AddField(
            model_name="artists",
            name="image_last_updated",
            field=models.DateTimeField(
                blank=True, help_text="When the image was last fetched", null=True
            ),
        ),
    ]
