# Generated by Django 5.2.4 on 2025-09-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_remove_artists_image_artists_cached_image_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artists",
            name="roster_number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Sequential number based on when artist was added (1st added = #1)",
                null=True,
                unique=True,
            ),
        ),
    ]
