# Generated by Django 5.2.4 on 2025-09-22 02:07

from django.db import migrations


def populate_roster_numbers(apps, schema_editor):
    """
    Populate roster numbers for existing artists based on their creation date
    First created artist gets roster number 1, and so on
    """
    Artists = apps.get_model('main', 'Artists')
    
    # Get all artists ordered by creation date (earliest first)
    artists = Artists.objects.all().order_by('created_at')
    
    # Assign roster numbers starting from 1
    for index, artist in enumerate(artists, start=1):
        artist.roster_number = index
        artist.save(update_fields=['roster_number'])
    
    print(f"Assigned roster numbers to {artists.count()} artists")


def reverse_populate_roster_numbers(apps, schema_editor):
    """
    Remove all roster numbers (for migration rollback)
    """
    Artists = apps.get_model('main', 'Artists')
    Artists.objects.all().update(roster_number=None)


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_artists_roster_number"),
    ]

    operations = [
        migrations.RunPython(
            populate_roster_numbers,
            reverse_populate_roster_numbers,
        ),
    ]
