# Generated by Django 5.2.4 on 2025-09-22 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_auto_20250922_0207"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="albums",
            options={"verbose_name": "Album", "verbose_name_plural": "Albums"},
        ),
        migrations.AlterModelOptions(
            name="artists",
            options={
                "ordering": ["roster_number"],
                "verbose_name": "Artist",
                "verbose_name_plural": "Artists",
            },
        ),
        migrations.AlterModelOptions(
            name="gamesubmission",
            options={
                "verbose_name": "Game Submission",
                "verbose_name_plural": "Game Submissions",
            },
        ),
        migrations.AlterModelOptions(
            name="labels",
            options={"verbose_name": "Label", "verbose_name_plural": "Labels"},
        ),
        migrations.AlterModelOptions(
            name="puzzle",
            options={"verbose_name": "Puzzle", "verbose_name_plural": "Puzzles"},
        ),
    ]
